# Your name and what you do
name: Shivam Kalra
bio: Deep-learning Researcher and Ph.D. Candidate

description: Shivam Kalra's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://shivamkalra.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: ShivamSkalra
linkedin: shivamkalra
github: shivamkalra
email: shivam.kalra@uwaterloo.ca
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Python, JS, Somewhat C/C++
    - Tensorflow, ML/data science packages
    - Distributed computing, Dask/Spark, MPI

# do you want to display a projects section? true or false
projects: false

# add your projects here
project-list:
    Eve:
        name: Eve
        description: Ultra Minimal Single-page Jekyll Template for Building Personal Portfolio Websites
        url: https://github.com/jibolash/Eve


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
